//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebClient.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.IServiceCalculator")]
    public interface IServiceCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/Sum", ReplyAction="http://tempuri.org/IServiceCalculator/SumResponse")]
        double Sum(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/Sum", ReplyAction="http://tempuri.org/IServiceCalculator/SumResponse")]
        System.Threading.Tasks.Task<double> SumAsync(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/Subtract", ReplyAction="http://tempuri.org/IServiceCalculator/SubtractResponse")]
        double Subtract(double firstNumber, double secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCalculator/Subtract", ReplyAction="http://tempuri.org/IServiceCalculator/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double firstNumber, double secondNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCalculatorChannel : MvcWebClient.CalculatorService.IServiceCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCalculatorClient : System.ServiceModel.ClientBase<MvcWebClient.CalculatorService.IServiceCalculator>, MvcWebClient.CalculatorService.IServiceCalculator {
        
        public ServiceCalculatorClient() {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Sum(double firstNumber, double secondNumber) {
            return base.Channel.Sum(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<double> SumAsync(double firstNumber, double secondNumber) {
            return base.Channel.SumAsync(firstNumber, secondNumber);
        }
        
        public double Subtract(double firstNumber, double secondNumber) {
            return base.Channel.Subtract(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double firstNumber, double secondNumber) {
            return base.Channel.SubtractAsync(firstNumber, secondNumber);
        }
    }
}
